name: Test
on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Autogen
        run: ./autogen.sh
      
      - name: Configure
        run: ./configure
      
      - name: make
        run: make
